/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HelloWorld {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PixBanner {
        "actionLabel": string;
        "actionUrl": string;
        "canCloseBanner": boolean;
        /**
          * Définit le type de bannière
         */
        "type": string;
    }
}
export interface PixBannerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPixBannerElement;
}
declare global {
    interface HTMLHelloWorldElement extends Components.HelloWorld, HTMLStencilElement {
    }
    var HTMLHelloWorldElement: {
        prototype: HTMLHelloWorldElement;
        new (): HTMLHelloWorldElement;
    };
    interface HTMLPixBannerElement extends Components.PixBanner, HTMLStencilElement {
    }
    var HTMLPixBannerElement: {
        prototype: HTMLPixBannerElement;
        new (): HTMLPixBannerElement;
    };
    interface HTMLElementTagNameMap {
        "hello-world": HTMLHelloWorldElement;
        "pix-banner": HTMLPixBannerElement;
    }
}
declare namespace LocalJSX {
    interface HelloWorld {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PixBanner {
        "actionLabel"?: string;
        "actionUrl"?: string;
        "canCloseBanner"?: boolean;
        "onClose"?: (event: PixBannerCustomEvent<any>) => void;
        /**
          * Définit le type de bannière
         */
        "type"?: string;
    }
    interface IntrinsicElements {
        "hello-world": HelloWorld;
        "pix-banner": PixBanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hello-world": LocalJSX.HelloWorld & JSXBase.HTMLAttributes<HTMLHelloWorldElement>;
            "pix-banner": LocalJSX.PixBanner & JSXBase.HTMLAttributes<HTMLPixBannerElement>;
        }
    }
}
